# Generated by Django 4.0.5 on 2022-08-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs_genre_alter_songs_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='file',
            new_name='audio',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='genre',
        ),
    ]
