# Generated by Django 4.0.5 on 2022-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_songs_file_songs_audio_songs_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='likes',
            field=models.PositiveIntegerField(),
        ),
    ]
