# Generated by Django 4.0.5 on 2022-08-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_songs_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
