# Generated by Django 4.0.5 on 2022-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='description',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
