# Generated by Django 4.0.5 on 2022-08-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
