# Generated by Django 4.0.5 on 2022-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_songs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
